### ISSUE TITLE
Memoria descriptiva y especificaciones tecnicas del proyecto

### ISSUE THREAD

**Issue by MirandaJorge** [Unahur/Programacion-PC2017#12]
Emision de la memoria descriptiva del proyecto para avance del equipo de programacion.
Emision de las especificaciones tecnicas para compra de los materiales.

**Comment by alecai11** [comment]
[Proyecto NodeMCU.docx](https://github.com/Unahur/Programacion-PC2017/files/1012870/Proyecto.NodeMCU.docx)
